### ISSUE TITLE
Convert failure 2

### ISSUE THREAD

**Issue by smallghost2** [EmmanuelBeziat/bns-profile#8]
Hi so I saw another post with the same issue but I never saw the solution to it. Same thing is happening to me, I hit convert and nothing happens. I did control shift j and this popped up:

vue.common.js:216 Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at VueComponent.UpdateChecksum (https://bns-profile.surge.sh/static/js/app.d4200450ccfb4a1491b4.js:10:3938)
    at VueComponent.UpdateChecksum (https://bns-profile.surge.sh/static/js/vendor.4ff40ada644a14fb4624.js:23:1149)
    at HTMLImageElement.n.onload (https://bns-profile.surge.sh/static/js/app.d4200450ccfb4a1491b4.js:10:3656)

I have no idea what to do ;- ; I use this all the time and this suddenly happened and I cant get it to work for the past 2 days. I'll post the pic I'm trying to convert.

http://imgur.com/AFwim5g

 Help? Thanks for reading. <3

**Comment by EmmanuelBeziat** [comment]
Hi,

The image is a PNG, it should be a JPG (weird, I thought I got rid of this png bug…).
Here's your final pic converted: https://image.noelshack.com/fichiers/2017/20/1494852087-bns-profile-2017-05-15-02-40.jpg

:)
